select count(*)from data.posts;
select count(*)from data.users;
select count(*)from data.replies;
select count(*)from data.secondary_replies;
select count(*) from relation.favorite_relation where post_id=163;
select count(*) from relation.favorite_relation where post_id=28;
select count(*) from relation.favorite_relation where post_id=6;
select count(*) from relation.share_relation where post_id=163;
select count(*) from relation.share_relation where post_id=28;
select count(*) from relation.share_relation where post_id=6;
select * from data.users where name='negative_mountain';
select * from data.users where name='helpful_understanding';
select * from data.users where name='overall_environment';
select post_id,cnt from(select post_id,tmp.cnt,dense_rank()over(order by cnt desc ) from(select post_id, count(*)cnt from relation.like_relation group by post_id) tmp)tmp1 where tmp1.dense_rank=1;
select follower_name from(select follower_name,dense_rank()over(order by cnt desc) from(select follower_name,count(*)cnt from relation.follow_relation  group by follower_name)tmp1)tmp2 where dense_rank=1;
select followee_name from(select followee_name,dense_rank()over(order by cnt desc) from(select followee_name,count(*)cnt from relation.follow_relation  group by followee_name)tmp1)tmp2 where dense_rank=1;
select post_id from data.posts order by posting_time;
select post_id from data.posts order by posting_time desc;
select * from data.users where name='novel_expert';
select post_id,cnt from(select post_id,tmp.cnt,dense_rank()over(order by cnt desc ) from(select post_id, count(*)cnt from relation.like_relation group by post_id) tmp)tmp1 where tmp1.dense_rank=1;
select post_id,cnt from(select post_id,tmp.cnt,dense_rank()over(order by cnt desc ) from(select post_id, count(*)cnt from relation.favorite_relation group by post_id) tmp)tmp1 where tmp1.dense_rank=1;
select post_id,cnt from(select post_id,tmp.cnt,dense_rank()over(order by cnt desc ) from(select post_id, count(*)cnt from relation.share_relation group by post_id) tmp)tmp1 where tmp1.dense_rank=1;
select follower_name ,cnt from(select follower_name,cnt,dense_rank()over(order by cnt desc) from(select follower_name,count(*)cnt from relation.follow_relation group by follower_name)tmp1)tmp2 where tmp2.dense_rank=1;
select followee_name ,cnt from(select followee_name,cnt,dense_rank()over(order by cnt desc) from(select followee_name,count(*)cnt from relation.follow_relation group by followee_name)tmp1)tmp2 where tmp2.dense_rank=1;
select * from data.posts order by posting_time limit 1;
select * from data.posts order by posting_time desc limit 1;
select count(*)from (select post_id,extract(year from posting_time)pst_time from data.posts)tmp where pst_time=2020;
select count(*)from (select post_id,extract(year from posting_time)pst_time from data.posts)tmp where pst_time=2021;
select count(*)from (select post_id,extract(year from posting_time)pst_time from data.posts)tmp where pst_time=2022;